export type Product = {
  code: string
  name: string
  image: string
  priceBasic: number
  priceLaminated: number
  category: string
  specifications: string[]
  badge?: string
}

export const WHATSAPP_NUMBER = "6281572070101"

export const products: Product[] = [
  {
  code: "LP2-SE000",
  name: "Basic Premium - Simple Elegant",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se000.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  
  {
  code: "LP2-SE001",
  name: "Basic Premium - Blush Romance ",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se001.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE002",
  name: "Basic Premium - Pure Botanical",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se002.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE003",
  name: "Basic Premium - Midnight Luxury",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se003.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE004",
  name: "Basic Premium - Sweet Watercolor",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se004.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE005",
  name: "Basic Premium - Tropical Breeze",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se005.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE006",
  name: "Basic Premium - Fresh Nature",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se006.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE007",
  name: "Basic Premium - Warm Rustic",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se007.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE008",
  name: "Basic Premium - Sky Blush",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se008.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE009",
  name: "Basic Premium - Minimalist Vine",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se009.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE010",
  name: "Basic Premium - Golden Leaf",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se010.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE011",
  name: "Basic Premium - Charcoal Gold",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se011.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE012",
  name: "Basic Premium - Greyish Bloom",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se012.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE013",
  name: "Basic Premium - Classic Baroque",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se013.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE014",
  name: "Basic Premium - Lace Floral",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se014.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE015",
  name: "Basic Premium - Royal Emblem",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se015.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE016",
  name: "Basic Premium - Spring Peony",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se016.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE017",
  name: "Basic Premium - Chic Botanical",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se017.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE018",
  name: "Basic Premium - Romantic Floral",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se018.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE019",
  name: "Basic Premium - Vintage Classic",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se019.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE020",
  name: "Basic Premium - Minimalist Cartoon",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se020.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE021",
  name: "Basic Premium - Botanical Elegance",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se021.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE022",
  name: "Basic Premium - Minimalist Lineart",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se022.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE023",
  name: "Basic Premium - Garden Blue",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se023.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE024",
  name: "Basic Premium - Geometric Purple",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se024.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE025",
  name: "Basic Premium - Luxury Gold",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se025.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE026",
  name: "Basic Premium - Natural Green",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se026.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-SE027",
  name: "Basic Premium - Beautiful Sketch",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-se027.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-wa000",
  name: "Watercolor - Earthy Abstract",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-wa000.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-wa001",
  name: "Watercolor - Emerald Emerald",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-wa001.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-wa002",
  name: "Watercolor - Midnight Dusk",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-wa002.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-wa003",
  name: "Watercolor - Terracotta Wash",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-wa003.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-wa004",
  name: "Watercolor - Tropical Monstera",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-wa004.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-wa005",
  name: "Watercolor - Ocean Splash",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-wa005.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-wa006",
  name: "Watercolor - Blue Marble",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-wa006.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-wa007",
  name: "Watercolor - The Forest",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-wa007.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-wa008",
  name: "Watercolor - Eucalyptus Garland",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-wa008.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-wa009",
  name: "Watercolor - Sage Splatter",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-wa009.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-wa010",
  name: "Watercolor - Pastel Foliage",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-wa010.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-wa011",
  name: "Watercolor - Ocean Mist",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-wa011.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-wa012",
  name: "Watercolor - Lavender Dream",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-wa012.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-wa013",
  name: "Watercolor - Dusty Rose",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-wa013.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-wa014",
  name: "Watercolor - The Mauve",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-wa014.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  {
  code: "LP2-wa015",
  name: "Watercolor - Cosmic Splash",
  category: "Lipat 2",
  priceBasic: 4500,
  priceLaminated: 6000,
  image: "/products/lp2-wa015.jpg",

  specifications: [
    "Ukuran 28 x 20 cm",
    "Kertas Art Paper 260 gsm",
    "Cetak Full Color",
    "Sudah include plastik OPP",
    "Bonus Kartu Nama (sesuai jumlah cetakan)",
    "Free Revisi (ganti warna, tambahan desain)",
    "Free Pengantaran (Area MTP & BJB)",
    "Minimal order 50 pcs",
"Pengerjaan 5-7 Hari",
  ],
},
  
]

export function formatRupiah(value: number): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value)
}

export function buildWhatsAppLink(product: Product): string {
  const message = `Halo Ka, saya tertarik memesan undangan cetak *${product.code} - ${product.name}*. Mohon info ketersediaan dan proses pemesanannya. Terima kasih!`
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`
}
